# Generated by Django 3.1.5 on 2021-02-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.FloatField(null=True)),
                ('night', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.FloatField(null=True)),
                ('night', models.FloatField(null=True)),
                ('minDay', models.FloatField(null=True)),
                ('maxDay', models.FloatField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='title',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='seconds',
        ),
        migrations.AddField(
            model_name='weather',
            name='dt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='humidity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='pop',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='pressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='rain',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='snow',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='wind_deg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='weatherTemp',
            field=models.ManyToManyField(to='weather.Temp'),
        ),
    ]
