# Generated by Django 3.1.5 on 2021-02-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210202_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='fellsLike',
            field=models.ManyToManyField(to='weather.Feels'),
        ),
    ]
