# Generated by Django 3.1.5 on 2021-02-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20210202_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='fellsLike',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='weatherTemp',
        ),
    ]
