# Generated by Django 3.1.5 on 2021-02-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20210202_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='fellsLike',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='weatherTemp',
        ),
        migrations.AddField(
            model_name='weather',
            name='dayFeel',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='dayTemp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='maxDayTemp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='minDayTemp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='nightFeel',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='nightTemp',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Feels',
        ),
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
